# Site settings
title: Introduction to statistics for geoscientists

name1: Gerard Gorman
address1: Room 4.92, Royal School of Mines
email1: g.gorman@imperial.ac.uk
github_username1:  ggorman
twitter_username1: gerardjgorman

description: > # this means to ignore newlines until "baseurl:"

  This lecture course has two objectives: learn basic statistical methods;
  become proficient in applying statistics using iPython.

baseurl: http://ggorman.github.io/Introduction-to-stats-for-geoscientists
production_url : http://ggorman.github.io/Introduction-to-stats-for-geoscientist

# Build settings
markdown: kramdown
future: true
